services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./schemas:/docker-entrypoint-initdb.d:z"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    image: node:current-alpine
    restart: always
    working_dir: "/home/node/app"
    volumes:
      - "./:/home/node/app:z"
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      API_PREFIX: ${API_PREFIX}
    command: "npm run start api"
  http:
    image: nginx
    restart: always
    volumes:
      - "./dist/apps/todo:/usr/share/nginx/html:z"
    ports:
      - ${NGINX_PORT}:80
