services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./schemas:/docker-entrypoint-initdb.d:z"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
