services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./schemas:/docker-entrypoint-initdb.d:z"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
  api:
      image: node:current-alpine
      restart: always
      working_dir: "/home/node/app"
      volumes:
        - "./:/home/node/app:z"
      ports:
        - 3333:3333
      command: "npm run start api"
  http:
      image: nginx
      restart: always
      volumes:
        - "./dist/apps/todo:/usr/share/nginx/html:z"
      ports:
        - 4200:80
  # app:
  #     image: node:current-alpine
  #     restart: always
  #     working_dir: "/home/node/app"
  #     volumes:
  #       - "./:/home/node/app:z"
  #     ports:
  #       - 4200:4200
  #     command: "npm run start"
